import logging
import os

import uvicorn
from dotenv import load_dotenv
from langchain.memory import ConversationBufferMemory
from langchain_community.tools.ddg_search import DuckDuckGoSearchRun
from langchain_community.vectorstores.pinecone import Pinecone
from langchain_experimental.tools import PythonREPLTool
from langchain_openai import OpenAIEmbeddings, ChatOpenAI

from agents.orchestrator_agent import OrchestratorAgent
from agents.vectorstore_agent import VectorStoreAgent
from documentation_loader import update_docs_database
from fastapi import FastAPI, Query, Body
from pydantic import BaseModel

from utils import env_variables_checker

app = FastAPI()
load_dotenv()
logger = logging.getLogger("Assistant")
INDEX_NAME = os.environ["INDEX_NAME"]

missing_variables = env_variables_checker()
if missing_variables:
    logging.warning(f'warning, you are missing the following env. variables: {missing_variables}')


vectorstore = Pinecone.from_existing_index(INDEX_NAME, OpenAIEmbeddings())
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.2, streaming=True)
documentation_agent = VectorStoreAgent(llm=llm, vectorstore=vectorstore)
# memory setup with resetting button.
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True,
                                  output_key="output")

tools = [DuckDuckGoSearchRun(name="Search"), PythonREPLTool(), documentation_agent.as_tool()]
orchestrator_agent = OrchestratorAgent(tools, llm, memory, return_intermediate_steps=True)



class Prompt(BaseModel):
    text: str


@app.get("/health")
async def health():
    """ Basic checking if the service is running"""
    return {"status": "I'm alive"}


@app.get("/update-docs")
async def update_docs_database_api(documentation_url: Prompt = Body(...)):
    """
    Updates the PINECONE database with new documents when called. It expects the document structure to be
    generated by Sphinx
    :param documentation_url: Optional argument if the url changes. defaults to https://ibm.github.io/ibm-generative-ai/
    """
    update_docs_database(documentation_url.text)


@app.post("/chat")
async def chat_api(prompt: Prompt = Body(...)):
    """
    Chat with the agent through an api by sending prompts
    :param prompt: user question or request
    :return:
    """

    response = orchestrator_agent.get_api_response(prompt.text)
    return response


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    uvicorn.run("api_interface:app")
