from documentation_loader import update_docs_database
from fastapi import FastAPI


app = FastAPI()


@app.post("/update-docs")
def update_docs_database_api(documentation_url: str):
    """
    Updates the PINECONE database with new documents when called. It expects the document structure to be
    generated by Sphinx.
    :param documentation_url: Optional argument if the url changes. defaults to https://ibm.github.io/ibm-generative-ai/
    """
    update_docs_database()


@app.post("/start-chat")
def start_chat_api(verbose: bool):
    """
    Starts chat with the agent through an api.
    :param verbose:
    :return:
    """
    